const KEY='radar_memory_v08'; const $=id=>document.getElementById(id); let data=JSON.parse(localStorage.getItem(KEY)||'[]');
const days=['domingo','lunes','martes','miércoles','jueves','viernes','sábado'];
function save(){localStorage.setItem(KEY,JSON.stringify(data));}
function norm(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function dateFromText(t){let n=new Date();let x=norm(t), d=null; if(/pasado manana/.test(x))d=new Date(n.setDate(n.getDate()+2)); else if(/\bmanana\b/.test(x))d=new Date(n.setDate(n.getDate()+1)); else {let m=x.match(/\b(lunes|martes|miercoles|jueves|viernes|sabado|domingo)\b/); if(m){let target=days.indexOf(m[1].replace('miercoles','miércoles').replace('sabado','sábado')); if(target>=0){let cur=new Date().getDay(),add=(target-cur+7)%7;if(add===0)add=7;d=new Date();d.setDate(d.getDate()+add)}}} return d;}
function timeFromText(t){let x=norm(t),m=x.match(/(?:a las|alas|a la)\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/); if(!m)m=x.match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b/); if(m){let h=+m[1],min=+(m[2]||0); if(m[3]==='pm'&&h<12)h+=12;if(m[3]==='am'&&h===12)h=0;return {h,min}} if(/en\s+una\s+hora/.test(x))return {relative:60}; let q=x.match(/dentro\s+de\s+(\d+)\s+minutos?/);if(q)return {relative:+q[1]}; return null;}
function analyze(text){let x=norm(text), intents=[],signals=[]; const add=(a,s)=>{if(!intents.includes(a))intents.push(a);if(s&&!signals.includes(s))signals.push(s)};
if(/\b(recu[eé]rdame|no quiero olvidar|no olvidarme|debo recordar|quiero recordar|tengo que recordar)\b/.test(text.toLowerCase()))add('recordatorio','recordatorio');
if(/\b(tengo que|tengo q|debo|hay que|me toca|toca)\b/.test(x))add('compromiso','compromiso');
if(/\b(quiero|quisiera|me gustaria|estoy pensando|estoy considerando|si pudiera|tal vez)\b/.test(x))add('intención','intencion');
if(/\b(necesito|necesito saber)\b/.test(x))add('necesidad','necesidad');
if(/\b(como puedo|como hago|no se como|ayudame)\b/.test(x))add('pregunta','pregunta');
if(/\b(me siento|estoy triste|estoy feliz|estoy enojado|estoy preocupado|me da miedo|tengo miedo|me estresa|estoy estresado)\b/.test(x))add('estado emocional','emocion');
if(/\b(ya hice|logre|termine|consegui|salio bien|funciono)\b/.test(x))add('logro/acción realizada','logro');
if(/\b(me preocupa|me da miedo|tengo miedo|me estresa|estres)\b/.test(x))add('preocupación','preocupacion');
let possibleExpense=/\b(comprar|pagar|gastar|cuesta|presupuesto|quetzales?|dinero|q\s*\d+)\b/i.test(text); if(possibleExpense)add('posible gasto','gasto');
let date=dateFromText(text), time=timeFromText(text); let explicitReminder=intents.includes('recordatorio'); let commitment=intents.includes('compromiso');
let shouldRemind=(explicitReminder||commitment)&& (date||time); let reminder=null;if(shouldRemind){let when=new Date(); if(date){when=new Date(date); if(time&&time.h!==undefined)when.setHours(time.h,time.min,0,0);else when.setHours(9,0,0,0)} else if(time&&time.relative){when.setMinutes(when.getMinutes()+time.relative)} else if(time){when.setHours(time.h,time.min,0,0)} reminder={when:when.toISOString(),text:text};}
return {intents,signals,date,time,reminder,possibleExpense};}
function renderResult(e,a){let lines=[]; lines.push(`<div class="result"><strong>🧠 Detecté:</strong> ${a.intents.length?a.intents.join(' · '):'información para tu contexto'}`); if(a.date){lines.push(`<div class="signal">📅 ${a.date.toLocaleDateString('es-GT',{weekday:'long',day:'numeric',month:'long'})}${a.time&&a.time.h!==undefined?' · '+String(a.time.h).padStart(2,'0')+':'+String(a.time.min).padStart(2,'0'):''}</div>`)} if(a.time&&a.time.relative){lines.push(`<div class="signal">⏰ En ${a.time.relative} minutos</div>`)} if(a.possibleExpense)lines.push('<div class="signal">💰 Posible gasto detectado</div>'); if(a.reminder)lines.push('<div class="signal">✓ Recordatorio creado</div>'); lines.push(`<div class="why">RADAR guardó esta entrada en tu memoria local.</div><div class="feedback"><button onclick="feedback('${e.id}','Superútil')">Superútil</button><button onclick="feedback('${e.id}','Bastante útil')">Bastante útil</button><button onclick="feedback('${e.id}','Regular')">Regular</button><button onclick="feedback('${e.id}','Poco útil')">Poco útil</button><button onclick="feedback('${e.id}','Nada útil')">Nada útil</button></div></div>`); $('result').innerHTML=lines.join('');}
window.feedback=(id,v)=>{let e=data.find(x=>x.id===id);if(e){e.feedback=v;save();$('result').insertAdjacentHTML('beforeend',`<div class="muted">Feedback guardado: ${v}</div>`)} };
$('detect').onclick=()=>{let text=$('input').value.trim();if(!text)return;let a=analyze(text);let e={id:crypto.randomUUID(),text,time:new Date().toISOString(),analysis:a,feedback:null};data.push(e);save();renderResult(e,a);$('input').value='';};
$('memoryBtn').onclick=()=>{let el=$('memory');el.classList.toggle('hidden');el.innerHTML='<h3>🧠 Memoria</h3>'+data.slice().reverse().map(e=>`<div class="item"><small>${new Date(e.time).toLocaleString('es-GT')}</small><br>${e.text}<br><span class="muted">${e.analysis.intents.join(' · ')||'contexto'}</span></div>`).join('')||'<p class="muted">Aún no hay memoria.</p>';};
$('summaryBtn').onclick=()=>{let el=$('summary');el.classList.toggle('hidden');let since=new Date();since.setHours(0,0,0,0);let today=data.filter(e=>new Date(e.time)>=since);let counts={};today.forEach(e=>e.analysis.intents.forEach(i=>counts[i]=(counts[i]||0)+1));let emotional=today.filter(e=>e.analysis.signals.includes('emocion')).length;el.innerHTML=`<h3>📋 Resumen de hoy</h3><p>RADAR registró <strong>${today.length}</strong> entradas.</p><p>🧠 ${Object.entries(counts).map(([k,v])=>`${k}: ${v}`).join(' · ')||'Todavía no hay suficientes señales.'}</p><p>❤️ Menciones emocionales: <strong>${emotional}</strong></p><p class="muted">Los patrones se irán formando con más información y feedback.</p>`;};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
